### ISSUE TITLE
Writing MapReduce jobs for Hadoop is HELL!

### ISSUE THREAD

**Issue by aalexandrov** [TU-Berlin-DIMA/IMPRO-3.SS14#36]

**Comment by oresti** [comment]
I almost got a heart attack. Dont joke like that :)

**Comment by aalexandrov** [comment]
I'm Sorry, I was making a point in the IMPRO-3 class that being open about the issues with your task at hand helps getting assistance. Bad wording, I actually didn't intend to submit.
